// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlIlBV0nWMH04rlCOn32goYRxVSpAMwGs',
    appId: '1:121820927719:web:4db2dcf877fd77ea5bb442',
    messagingSenderId: '121820927719',
    projectId: 'laundry-ab95e',
    authDomain: 'laundry-ab95e.firebaseapp.com',
    storageBucket: 'laundry-ab95e.appspot.com',
    measurementId: 'G-3L0T4EKGZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzhwQigFW2_D3XpoQaAmbmW2A6OKEXJZk',
    appId: '1:121820927719:android:01702bb2bed0cada5bb442',
    messagingSenderId: '121820927719',
    projectId: 'laundry-ab95e',
    storageBucket: 'laundry-ab95e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLdAsol6blVQy5n-HCChnqlugd5NDEEbM',
    appId: '1:121820927719:ios:f3594d1bc93d1d3c5bb442',
    messagingSenderId: '121820927719',
    projectId: 'laundry-ab95e',
    storageBucket: 'laundry-ab95e.appspot.com',
    iosClientId: '121820927719-la6jss6rn674fs30mddmtdg0o2lhsv3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.laundryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLdAsol6blVQy5n-HCChnqlugd5NDEEbM',
    appId: '1:121820927719:ios:f3594d1bc93d1d3c5bb442',
    messagingSenderId: '121820927719',
    projectId: 'laundry-ab95e',
    storageBucket: 'laundry-ab95e.appspot.com',
    iosClientId: '121820927719-la6jss6rn674fs30mddmtdg0o2lhsv3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.laundryApp',
  );
}
